export const GET_APPLICATIONS = 'GET_APPLICATIONS';
export const ADD_APPLICATION = 'ADD_APPLICATION';
export const DELETE_APPLICATION = 'DELETE_APPLICATION';
export const UPDATE_APPLICATION_STATE = 'UPDATE_APPLICATION_STATE';
export const UPDATE_APPLICATION_DECISION = 'UPDATE_APPLICATION_DECISION';
export const UPDATE_APPLICATION_MEETING = 'UPDATE_APPLICATION_MEETING';
export const APPLICATIONS_LOADING = 'APPLICATIONS_LOADING';

export const GET_AVAILABILITIES = 'GET_AVAILABILITIES';
export const ADD_AVAILABILITY = 'ADD_AVAILABILITY';
export const DELETE_AVAILABILITY = 'DELETE_AVAILABILITY';
export const UPDATE_AVAILABILITY = 'UPDATE_AVAILABILITY';
export const AVAILABILITIES_LOADING = 'AVAILABILITIES_LOADING';
