export const GET_APPLICATIONS = 'GET_APPLICATIONS';
export const ADD_APPLICATION = 'ADD_APPLICATION';
export const DELETE_APPLICATION = 'DELETE_APPLICATION';
export const APPLICATIONS_LOADING = 'APPLICATIONS_LOADING';
